version: 2

sources:
  - name: qwt_raw
    database: "{{env_var('DBT_DBNAME','QWT_ANALYTICS')}}"
    schema: "{{env_var('DBT_RAWSCHEMA','RAW')}}"
    tables:
      - name: raw_customers
      - name : raw_products
      - name : raw_orders
      - name : raw_order_details
      - name : raw_offices
      - name : raw_employees
      - name : raw_shipments
      - name : raw_suppliers
